apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/component=webhook,app.kubernetes.io/instance=default,app.kubernetes.io/name=webhook,app.kubernetes.io/part-of=tekton-pipelines
    backstage.io/kubernetes-namespace: tekton-pipelines
  description: Tekton Pipelines Webhook Component
  name: tekton-pipelines-webhook
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: tekton
  type: service
