apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app=api-portal-server
    prometheus.io/rule: sum(container_memory_working_set_bytes{job="kubelet", metrics_path="/metrics/cadvisor", cluster="", namespace="accelerator-system", pod="acc-engine-548f89484-vffz8", image!=""}) by (container) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster="", namespace="accelerator-system", pod="acc-engine-548f89484-vffz8"}) by (container)
  description: Tanzu API Portal Component
  name: api-portal
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: api-portal
  type: service
