apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app=api-portal-server
  description: Tanzu API Portal Component
  name: api-portal
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: api-portal
  type: service
