apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: deployment=learningcenter-portal
  description: Learing Center Portal Component
  name: learning-center-portal
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: learning-center
  type: service
