apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=services-toolkit-controller-manager
    backstage.io/kubernetes-namespace: services-toolkit
  description: Services Toolkit Controller Component
  name: services-toolkit-controller
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: services-toolkit
  type: service
