apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: Tanzu Application Accelerator System
  name: application-accelerator
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  domain: tap
  owner: platform-team
